(() => {
  "use strict";

  const posts = [
    {
      slug: "what-should-a-company-ai-remember",
      title: "What Should a Company’s AI Remember?",
      subtitle: "From chat history to governed organizational memory",
      question: "How can an organization learn from its work without turning every conversation into permanent model memory?",
      project: "Enterprise Context & Organizational Memory Lab",
      projectLink: "../projects/enterprise-context-memory.html",
      evidence: "Future research · synthetic case study",
      theme: "Enterprise Context",
      time: "10 min",
      featured: true,
      summary: "A practical explanation of context, retrieval, user memory, organizational learning, permission, and the data platform required to keep them separate.",
      full: true,
      sections: [
        ["A company is not one document collection", [
          "Enterprise knowledge lives in many forms. Policies are documents. Sales orders are structured records. Machine condition is a changing stream. A project decision may live in a meeting transcript. A useful troubleshooting lesson may exist only in the experience of two engineers. These sources have different owners, freshness, sensitivity, and authority. Treating them as equal chunks in one vector database loses those differences.",
          "The problem is better described as context engineering than as “training a company LLM.” The model supplies general language and reasoning capability. The surrounding platform decides what organizational information is relevant, permitted, current, and trustworthy enough to use."
        ]],
        ["Context, memory, and learning are different", [
          "If an employee asks for the current warranty escalation rule, the AI should retrieve the approved policy. It does not need to learn that rule into model weights. A project mentioned during one conversation can remain session context. An explicit preference for architecture diagrams may become user-controlled memory. None of these requires retraining the model.",
          "Organizational learning is different. A useful diagnostic procedure discovered during repeated investigations should move through a pipeline: candidate lesson, supporting and contradictory evidence, review, ownership, approval, versioning, access policy, and expiry. The reusable object is validated knowledge—not the raw conversation."
        ]],
        ["Case study: a factory question that begins as conversation", [
          "Consider a synthetic factory scenario where Line 3 loses productivity after maintenance. An operator asks why output is down. Because the question is company-specific and time-sensitive, the system needs current MES data, telemetry, maintenance records, quality results, incidents, shift context, and procedures. A general list of possible causes is not enough.",
          "During retrieval, the system finds a previous engineering conversation: a similar machine once showed rising vibration after its lubrication interval was extended. That statement is useful, but it remains a hypothesis. The AI attaches it to the investigation with provenance instead of promoting it into company truth.",
          "Historical incidents partly support the pattern, and a reliability engineer approves a narrower diagnostic rule. The reviewed lesson receives machine-family scope, an owner, evidence, access policy, validity period, and supersession history. Future investigations may retrieve it; contradictory evidence can later revise or expire it."
        ]],
        ["Why this is a data-engineering problem", [
          "The model is only one component. The system needs identity, access policy, source metadata, event timestamps, lineage, live-state reconstruction, retrieval, conflict handling, retention, evaluation data, audit trails, and cost attribution. It must distinguish current telemetry from historical context and relevant evidence from authorized evidence.",
          "Enterprise context is a data product with quality, ownership, freshness, provenance, and consumers. Organizational memory is another data product with a lifecycle—not an unlimited accumulation of text."
        ]],
        ["Should company AI learn employee behavior?", [
          "There is a useful version of personalization and a dangerous one. Remembering a role, approved projects, preferred language, or explanation depth can reduce friction when the employee can inspect and control it. Silently inferring attitude, loyalty, performance, health, personality, or likelihood to leave is a different category of system.",
          "The design direction is to keep private assistance memory separate from shared organizational memory. Learn how to help a worker perform a task; do not turn ordinary work conversations into a hidden surveillance dataset."
        ]],
        ["Measure the workflow, not only the tokens", [
          "A realistic enterprise task may use an LLM, retrieval index, knowledge graph, database query, tool API, memory store, observability platform, and data pipeline. Cost should be measured at the workflow level: cost per assist, investigation, approved action, or case resolved.",
          "That makes optimization meaningful. A small model can handle simple policy-location questions; a stronger model may be justified for a complex incident. Retrieval can be cached, and context can be reduced instead of sending the company’s entire history with every prompt."
        ]],
        ["The future project", [
          "The Enterprise Context & Organizational Memory Lab will test this architecture in a small synthetic industrial setting. It will classify general versus company questions, enforce authorization before retrieval, assemble current operational context, extract candidate lessons from synthetic interactions, require review before memory is written, and measure whether the memory improves later investigations.",
          "The longer research direction connects approved knowledge to root-cause investigation, digital-twin experiments, maintenance recommendations, and bounded physical-operation decisions while keeping deterministic safety and accountable human authority outside the LLM."
        ]]
      ],
      sources: [
        ["Microsoft Azure Architecture Center — AI overview and context engineering", "https://learn.microsoft.com/en-us/azure/architecture/ai-ml/ai-overview"],
        ["Microsoft Research — From raw interaction to reusable knowledge", "https://www.microsoft.com/en-us/research/blog/from-raw-interaction-to-reusable-knowledge-rethinking-memory-for-ai-agents/"],
        ["Microsoft Research — GroupMemBench", "https://arxiv.org/abs/2605.14498"],
        ["Enterprise retrieval and tool-use security research", "https://arxiv.org/abs/2605.05287"],
        ["Microsoft Research — Risks in AI-mediated enterprise knowledge access", "https://www.microsoft.com/en-us/research/publication/a-framework-for-exploring-the-consequences-of-ai-mediated-enterprise-knowledge-access-and-identifying-risks-to-workers/"],
        ["FinOps Foundation — Unit economics", "https://www.finops.org/framework/capabilities/unit-economics/"],
        ["IBM — Context engineering for trusted agentic AI", "https://www.ibm.com/think/insights/context-engineering-foundation-trusted-ai"]
      ]
    },
    {
      slug: "pipeline-succeeded-data-wrong", title: "The Pipeline Succeeded. Why Was the Data Still Wrong?", question: "What should happen when compute succeeds but the data product is unsafe?", project: "AI-Assisted Data Reliability Platform", projectLink: "../projects/ai-data-reliability.html", evidence: "Implemented local reference path", theme: "Data Reliability", time: "7 min", summary: "Follow one payment incident through contracts, quarantine, reconciliation, evidence, human review, and guarded response.", scenario: "A payment job returns success while one source is missing or structurally changed. The publication gate must respond to the evidence, not only the scheduler status.", hiddenFailure: "A green job state says that code completed. It does not prove completeness, freshness, schema compatibility, uniqueness, or reconciliation.", engineering: "Preserve source identity and run metadata, validate contracts, quarantine invalid records, reconcile source and target, derive incidents from deterministic evidence, and require approval for consequential action.", next: "Add a duplicate-payment-batch scenario and strengthen operational metadata without weakening idempotency or reset safety."
    },
    {
      slug: "faster-is-not-better", title: "Faster Is Not Better If the Data Changes", question: "Can a performance improvement be accepted before correctness is reconciled?", project: "Data Pipeline Optimization Framework", projectLink: "../projects/pipeline-optimization.html", evidence: "Active development · results not measured", theme: "Performance", time: "6 min", summary: "Why optimization begins with one controlled change, a reproducible workload, and like-for-like output checks.", scenario: "Compare CSV and Parquet, partition strategy, broadcast joins, or caching while reconciling row counts, keys, and measures before accepting a speedup.", hiddenFailure: "A lower runtime can conceal changed results, warm-cache bias, different hardware, skew, or an unrecorded workload change.", engineering: "Version the dataset, machine profile, configuration, transformation, and metrics. Change one variable, retain Spark evidence, and reject candidates that fail output reconciliation.", next: "Publish the first baseline and comparison report with runtime, correctness, configuration, and machine context."
    },
    {
      slug: "service-tickets-trusted-data-product", title: "From Service Tickets to a Trusted Industrial Data Product", question: "How do fragmented service records become a decision-ready product?", project: "Industrial Service Intelligence Platform", projectLink: "../projects/industrial-service-intelligence.html", evidence: "Active development · synthetic data", theme: "Industrial Intelligence", time: "6 min", summary: "Start with the operational decision, preserve source grain, and make service metrics traceable.", scenario: "Investigate repeat visits for one machine family across ticket, asset, warranty, dealer, part, and maintenance records.", hiddenFailure: "A polished dashboard can mix tickets, visits, work orders, and parts at incompatible grains and still look plausible.", engineering: "Define source grain, conformed business keys, quality rules, metric ownership, and lineage before serving SLA risk, repeat visits, and customer impact.", next: "Complete the synthetic model, trusted service metrics, and one evidence-backed investigation path."
    },
    {
      slug: "nearest-robot-not-best", title: "Why the Nearest Robot Is Not Always the Best Robot", question: "What changes when asset health becomes a scheduling constraint?", project: "Health-Aware Robotic Fleet Optimization", projectLink: "../projects/robotic-fleet-optimization.html", evidence: "Research blueprint · no simulator result", theme: "Optimization", time: "6 min", summary: "Availability and distance are incomplete when battery, health, workload, task priority, and risk shape assignment.", scenario: "A high-priority task arrives while the nearest robot has low battery and a degraded health score. Compare it with a constrained alternative assignment.", hiddenFailure: "Nearest-available logic can create avoidable charging, failure exposure, workload imbalance, or missed deadlines.", engineering: "Build synthetic fleet state, explicit hard constraints, an availability-only baseline, a health-aware scheduler, and replayable decision reports.", next: "Implement a deterministic simulator before introducing learned health estimates or agent coordination."
    },
    {
      slug: "dashboard-is-not-data-product", title: "A Dashboard Is Not a Data Product", question: "What must be true before a retail metric deserves a chart?", project: "Retail Sales and Inventory Intelligence", projectLink: "../projects/retail-inventory-intelligence.html", evidence: "Parked · future domain transfer", theme: "Data Architecture", time: "5 min", summary: "Sales events and inventory snapshots keep different grains; useful metrics begin with modeling and definitions.", scenario: "Identify a store-product combination that looks healthy in sales but is approaching stockout, then trace the conclusion to sales and inventory facts.", hiddenFailure: "Joining transaction and snapshot data without grain discipline can multiply rows and create plausible but wrong metrics.", engineering: "Separate facts, define keys and time semantics, validate inventory movement, publish metric contracts, and preserve drill-through evidence.", next: "Resume only after stronger evidence in the core portfolio; forecasting and ROI remain future work."
    },
    {
      slug: "ai-suggest-cause-not-declare", title: "AI Can Suggest a Cause. It Should Not Declare One.", question: "How should an AI-assisted investigation expose evidence and uncertainty?", project: "Manufacturing Root-Cause Analysis Assistant", projectLink: "../projects/manufacturing-root-cause.html", evidence: "Evolving research concept", theme: "Industrial Intelligence", time: "7 min", summary: "Root-cause assistance is safer when hypotheses, support, contradiction, missing evidence, and human judgment stay visible.", scenario: "A defect spike appears on one machine and shift. Compare machine, process, inspection, maintenance, and contextual records before proposing a hypothesis.", hiddenFailure: "A fluent narrative can collapse correlation into cause and hide missing or contradictory evidence.", engineering: "Retrieve traceable evidence, preserve timestamps and grain, label hypotheses, surface conflicts, record missing checks, and require engineer review.", next: "Integrate a bounded investigation module into the Industrial Service Intelligence project."
    },
    {
      slug: "simulate-before-decision", title: "Simulate the Decision Before You Make It", question: "Can a digital twin become a verification boundary?", project: "Supply Chain Digital Twin Research Lab", projectLink: "../projects/supply-chain-digital-twin.html", evidence: "Research blueprint · no measured outcomes", theme: "Digital Twins", time: "6 min", summary: "A decision sandbox compares policies against the same validated state, assumptions, uncertainty, and outcome measures.", scenario: "Compare inventory reallocation and recovery policies under one disruption across backlog, service, cost, and recovery time.", hiddenFailure: "A visual twin can look authoritative while using inconsistent initial state, hidden assumptions, or incomparable scenarios.", engineering: "Version the state, scenario, policy, random seed, constraints, simulator, and outcomes so every comparison can be replayed.", next: "Build the validated state model and a deterministic reference simulation."
    },
    {
      slug: "index-helps-workload", title: "When Does an Index Help the Workload, Not Just One Query?", question: "What evidence proves a database change improves the system?", project: "Database Performance and Workload Lab", projectLink: "../projects/database-performance-lab.html", evidence: "Research blueprint · benchmark planned", theme: "Performance", time: "6 min", summary: "Move beyond one query to p50/p95 latency, throughput, plans, write cost, storage, and concurrency.", scenario: "Compare a baseline and candidate index under a controlled read/write mix and repeatable cache conditions.", hiddenFailure: "One faster query can conceal slower writes, storage growth, plan instability, tail latency, or lock contention.", engineering: "Version data shape, workload, concurrency, cache state, configuration, query plans, latency distributions, throughput, and correctness.", next: "Define the workload generator and publish the first reproducible baseline."
    },
    {
      slug: "architecture-to-business-value", title: "From Architecture Diagram to Business Value", question: "How does a technical intervention become a measurable business hypothesis?", project: "Product and Business Case Studies", projectLink: "../projects/business-case-studies.html", evidence: "Case-study track · assumptions explicit", theme: "Business / Product", time: "5 min", summary: "Connect user problems, baseline work, architecture, metrics, adoption risk, and transparent value ranges.", scenario: "Take one industrial AI proposal and map the current workflow, intervention, measurable hypothesis, adoption constraints, and evidence needed for a decision.", hiddenFailure: "Architecture can become solution theater when the user decision, baseline, cost, risk, and validation plan are left implicit.", engineering: "Separate facts from assumptions, define the value unit, connect technical measures to operating outcomes, and include sensitivity and adoption constraints.", next: "Publish the first complete case using evidence already present in the portfolio."
    },
    {
      slug: "shortest-drone-route-wrong", title: "When the Shortest Drone Route Is the Wrong Route", question: "When do environment and vehicle health change the preferred inspection mission?", project: "Environmental & Health-Aware Drone Fleet Intelligence", projectLink: "../projects/drone-fleet-intelligence.html", evidence: "Research blueprint · implementation next", theme: "Physical Intelligence", time: "7 min", summary: "Distance-only routing is an incomplete baseline when wind, reserve, health, communication, fleet workload, and inspection priority matter.", scenario: "Assign several industrial inspection tasks across a small synthetic fleet under changing wind and battery conditions.", hiddenFailure: "The shortest route can consume more energy, enter communication gaps, stress degraded components, or leave an unsafe return reserve.", engineering: "Create versioned mission, fleet, environment, health, and decision data; compare transparent planners in a replayable simulator; keep hard constraints outside the LLM.", next: "Build Phase 1: deterministic laptop simulation with synthetic data and no field-performance claim."
    },
    {
      slug: "elevator-scheduling-decisions", title: "Can an Elevator System Explain and Improve Its Own Scheduling Decisions?", question: "How might enterprise context, simulation, and safe control meet in a smart building?", project: "Future ElevateIQ direction", projectLink: "../index.html#enterprise-physical", evidence: "Future concept · no implementation", theme: "Physical Intelligence", time: "5 min", summary: "A second physical-intelligence scenario connecting passenger demand, equipment health, energy, scheduling, simulation, and controller boundaries.", scenario: "Morning queue congestion raises waiting time. Compare the current policy with a simulated candidate while monitoring energy, p95 wait, utilization, and health constraints.", hiddenFailure: "An optimization can improve average wait while worsening tail latency, energy, equipment stress, accessibility, or emergency behavior.", engineering: "Preserve event identity, demand state, car health, policy version, simulator inputs, constraints, decision trace, and measured outcomes.", next: "Keep this as a future direction until a deterministic simulation and evidence model exist."
    }
  ];

  const bySlug = Object.fromEntries(posts.map((post) => [post.slug, post]));
  const root = document.querySelector("[data-blog-root]");
  if (!root) return;

  const header = () => `<a class="skip-link" href="#blog-main">Skip to content</a><header class="blog-header"><nav class="blog-nav"><a class="blog-brand" href="../index.html"><span aria-hidden="true">SK</span><b>Sourav Khandai</b></a><div><a href="../index.html">Portfolio</a><a href="../index.html#projects">Projects</a><a href="../index.html#company-context">Context &amp; Memory</a><a href="index.html">All stories</a></div></nav></header>`;
  const footer = () => `<footer class="blog-footer"><div><p>© 2026 Sourav Khandai</p><p>Reliable systems · honest evidence · human judgment</p><a href="#blog-main">Back to top ↑</a></div></footer>`;
  const card = (post) => `<article class="blog-card" data-theme="${post.theme}"><div class="blog-card-meta"><span>${post.theme}</span><span>${post.evidence}</span></div><h2>${post.title}</h2><p class="blog-card-question">${post.question}</p><p>${post.summary}</p><div class="blog-card-footer"><span>${post.project} · ${post.time}</span><a href="${post.slug}.html" aria-label="Read ${post.title}">Read story <span aria-hidden="true">→</span></a></div></article>`;

  if (document.body.hasAttribute("data-blog-index")) {
    const themes = ["All", ...new Set(posts.map((post) => post.theme))];
    root.innerHTML = `${header()}<main id="blog-main"><section class="blog-index-hero"><div><p class="blog-kicker">Research notes &amp; project stories</p><h1>The reasoning behind the systems.</h1><p>Project pages hold architecture, status, and evidence. These companion stories explain the operating problem, hidden failure mode, engineering question, concrete scenario, limitations, and next experiment.</p></div><aside><strong>${posts.length}</strong><span>stories and blueprints</span><p>Measured, synthetic, planned, and research-only claims remain visibly distinct.</p></aside></section><section class="blog-index"><div class="blog-filters" role="group" aria-label="Filter stories">${themes.map((theme, index) => `<button type="button" data-blog-filter="${theme}" aria-pressed="${index === 0}">${theme}</button>`).join("")}</div><p class="blog-filter-status" aria-live="polite">${posts.length} stories shown</p><div class="blog-grid">${posts.map(card).join("")}</div></section></main>${footer()}`;
    document.querySelectorAll("[data-blog-filter]").forEach((button) => button.addEventListener("click", () => {
      const theme = button.dataset.blogFilter;
      document.querySelectorAll("[data-blog-filter]").forEach((item) => item.setAttribute("aria-pressed", String(item === button)));
      let visible = 0;
      document.querySelectorAll(".blog-card").forEach((item) => { const show = theme === "All" || item.dataset.theme === theme; item.hidden = !show; if (show) visible += 1; });
      document.querySelector(".blog-filter-status").textContent = `${visible} ${visible === 1 ? "story" : "stories"} shown · ${theme}`;
    }));
    return;
  }

  const post = bySlug[document.body.dataset.blogSlug];
  if (!post) { root.innerHTML = `${header()}<main id="blog-main" class="blog-not-found"><h1>Story not found</h1><a href="index.html">Browse all stories</a></main>${footer()}`; return; }

  const standardBody = `<section><h2>1. The operating problem</h2><p>${post.summary}</p></section><section><h2>2. Why the obvious solution is incomplete</h2><p>${post.hiddenFailure}</p></section><section><h2>3. The engineering question</h2><blockquote>${post.question}</blockquote></section><section><h2>4. Case study / scenario</h2><p>${post.scenario}</p></section><section><h2>5. Architecture and decisions</h2><p>${post.engineering}</p></section><section class="article-evidence"><h2>6. Evidence and limits</h2><p><strong>${post.evidence}.</strong> This article is a companion blueprint based on the portfolio’s current evidence. It does not add results, users, deployments, or measured benefits that the project has not demonstrated.</p></section><section><h2>7. What I would test next</h2><p>${post.next}</p></section>`;
  const fullBody = post.full ? post.sections.map(([title, paragraphs], index) => `<section><h2>${index + 1}. ${title}</h2>${paragraphs.map((paragraph) => `<p>${paragraph}</p>`).join("")}</section>`).join("") + `<section class="article-evidence"><h2>${post.sections.length + 1}. Evidence and limits</h2><p><strong>${post.evidence}.</strong> The Line 3 example is synthetic, the future project is not deployed inside a real employer, and no real employee conversations are used. The architecture and research questions are available; implementation results are not yet claimed.</p></section><section class="article-sources"><h2>Research references</h2><ol>${post.sources.map(([name, href]) => `<li><a href="${href}">${name} <span aria-hidden="true">↗</span></a></li>`).join("")}</ol></section>` : "";
  root.innerHTML = `${header()}<main id="blog-main"><article><header class="article-hero"><div class="article-meta"><span>${post.theme}</span><span>${post.evidence}</span><span>${post.time} read</span></div><h1>${post.title}</h1>${post.subtitle ? `<p class="article-subtitle">${post.subtitle}</p>` : ""}<p class="article-question">${post.question}</p><div class="article-links"><a href="${post.projectLink}">Related project <span aria-hidden="true">→</span></a><a href="index.html">All stories</a></div></header><div class="article-layout"><aside class="article-rail"><span>Related project</span><strong>${post.project}</strong><p>${post.evidence}</p><a href="${post.projectLink}">View architecture and evidence →</a></aside><div class="article-body">${post.full ? fullBody : standardBody}</div></div></article><nav class="article-next" aria-label="Continue reading"><a href="${post.projectLink}"><span>Return to the engineering record</span><strong>${post.project}</strong></a><a href="index.html"><span>Explore the collection</span><strong>All research notes &amp; stories</strong></a></nav></main>${footer()}`;
})();
